# Generated by Django 3.1.13 on 2022-02-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate_number', models.TextField(default='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
