# Generated by Django 3.1.13 on 2022-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp', '0002_date_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_vehicle',
            name='mileage',
            field=models.TextField(default=''),
        ),
    ]
