# Generated by Django 3.1.13 on 2022-02-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ')),
                ('number_plate', models.TextField(default=' ')),
                ('color', models.TextField(default=' ')),
            ],
        ),
    ]
