# Generated by Django 3.1.13 on 2022-02-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_number', models.IntegerField()),
            ],
        ),
    ]
